### ISSUE TITLE
Feature: clearCache for specific entity instead of all entities

### ISSUE THREAD

**Issue by pentateu** [ice-services/moleculer-addons#5]
Hi,

This a question / feature request.

Any specific reason why u clear all entities related to the service in the clearCache? 
clearCache() {
			this.broker.emit("cache.clean", this.name + ".*");
			return this.Promise.resolve();
		},

Have u considered removing just the entity being impacted by an update/delete?

I'm considering doing a PR with this feature, but would like to hear from u first.

**Comment by icebob** [comment]
Hi,

it is not so easy. Because if the `list` and `find` actions store the whole results in the cache. If one record changed, you need to clear these entries as well.

But you can change these logic, if you overwrite the `clearCache` method in your service.

```js
module.exports = {
  mixins: [DbService],
  methods: {
    clearCache() {
        ...
    }  
}
}
```
